// Auto-generated by https://github.com/react-spring/gltfjsx

import * as THREE from "three"
import React, { useEffect, useRef, useState } from "react"
import { useLoader, useFrame } from "react-three-fiber"
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader"
//import { draco } from 'drei'

const defaultURL = "https://tseijp-static.s3.ap-northeast-1.amazonaws.com/Xbot.glb"

export const Model = ({
    url=defaultURL,dark=true, size=50, position=[0,-11,0],scale=[7,7,7]}:any) => {
    const {animations, nodes}:any = useLoader(GLTFLoader, url, )
    const group = useRef<any>(null)
    const actions = useRef<any>(null)
    const [mixer] = useState<any>(() => new THREE.AnimationMixer(null as any))
    const modelPos  = {x:position[0],y:position[2]}
    useFrame(({camera}:any, delta)=>{
        mixer.update(delta)
        if(! group?.current?.position) return
        group.current.position.x = modelPos.x
        group.current.position.z = modelPos.y
        camera.updateProjectionMatrix(void (
            camera.lookAt(new THREE.Vector3(modelPos.x/2,0,modelPos.y/2))))
    })
    useEffect(() => {
        const actionNum = size > 50 ? 3 : 1
        actions.current = { idle: mixer.clipAction(animations[actionNum], group.current) }
        actions.current.idle.play()
        actions.current.idle.weight = 1
        actions.current.idle.timeScale = 1
        console.log(actions.current.idle)
        return () => animations.forEach((clip:any) => mixer.uncacheClip(clip))
    }, [animations,mixer,size])
    if (!nodes)
        return null
    return (
        <group ref={group} {...{position, scale}} dispose={null}>
          <group rotation={[Math.PI/2,0,0]} scale={[0.01,0.01,0.01]}>
            <primitive object={nodes["mixamorigHips"]} />
            <skinnedMesh geometry={nodes["Beta_Joints"].geometry}
                skeleton={nodes["Beta_Joints"].skeleton}
                rotation={[-Math.PI/2,0,0]} scale={[100, 100, 100]}>
                <meshPhongMaterial
                    attach="material" color={dark?0x212121:0x000000}
                    depthWrite={false} skinning />
            </skinnedMesh>
            <skinnedMesh geometry={nodes["Beta_Surface"].geometry}
                skeleton={nodes["Beta_Surface"].skeleton}
                rotation={[-Math.PI/2,0,0]} scale={[100, 100, 100]}>
                <meshPhongMaterial
                    attach="material" color={dark?0x000000:0xffffff}
                    depthWrite={false} skinning />
            </skinnedMesh>
          </group>
        </group>
    )
}
